# Generated by Django 2.2.7 on 2019-11-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('idade', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=13)),
                ('responsavel', models.CharField(max_length=150)),
                ('pesquisador', models.CharField(max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('idade', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=13)),
                ('responsavel', models.CharField(max_length=150)),
                ('pesquisador', models.CharField(max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('nome_do_telemarketing', models.CharField(max_length=150)),
                ('parentesco', models.CharField(max_length=50)),
                ('escola', models.CharField(max_length=200)),
                ('turno', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('Endereco', models.CharField(max_length=300)),
                ('CEP', models.CharField(max_length=8)),
                ('Cidade', models.CharField(max_length=60)),
                ('Estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=60)),
                ('codigo_telemarketing', models.CharField(max_length=30)),
                ('data_agendamento', models.DateField(auto_now=True)),
                ('observacoes', models.TextField()),
                ('status', models.CharField(choices=[['A', 'Atendeu'], ['N', 'Não Atendeu'], ['C', 'Caixa de Mensagens']], max_length=1)),
            ],
        ),
    ]
